### ISSUE TITLE
Begriff Himmelsrichtungen

### ISSUE THREAD

**Issue by Manu3l0us** [renestraub/ehk1#1]
Ich bin die Lektion zur Gravitation durchgegangen, soweit so gut. Irgendwie finde ich aber, der Begriff Himmelsrichtungen passt nicht so gut. Müsste man nicht eher von Achsen sprechen? Oder vielleicht hast du noch eine bessere Idee?

**Comment by renestraub** [comment]
Völlig einverstanden. Ich schaue mir das an und ersetze den Begriff. Bei Achsen kommt aber spontan ein Zweiachser LKW in den Sinn ;-)
